---
- name: install docker and docker-compose
  hosts: aws_ec2
  become: yes
  tasks:
  - name: installing docker, pip and python3
    yum:
      name: "{{ packages }}"
      update_cache: yes
      state: present
    vars:
      packages:
      - docker
      - python3
      - pip
    register: docker_log
  
  - name: install docker python module
    pip:
      name: docker

  - name: start docker service
    ansible.builtin.service:
      name: docker 
      state: started
      enabled: yes

  - name: downloading docker compose binaries
    ansible.builtin.get_url:
     url: https://github.com/docker/compose/releases/download/1.23.2/docker-compose-linux-x86_64
     dest: /usr/local/bin/docker-compose
     mode: +x

 

  - name: Add ec2-user group to docker group to be able to run docker commands
    ansible.builtin.user:
      name: ec2-user
      group: docker
      append: yes
  

  - name: reconnect for server session
    ansible.builtin.meta: reset_connection

  

      
      

# - name: test docker with an image pull
#   hosts: all
#   become_user: ec2-user
#   tasks:
#   - name: pull and run an image
#     ansible.builtin.docker_image:
#      name: redis
#      source: pull
     



      
  



    
    
    
    



      

